### ISSUE TITLE
Usage instructions

### ISSUE THREAD

**Issue by StandBackBurrito** [Microsoft/VisualStudioUninstaller#6]
Could you please post how to use this in the readme or the wiki.

I have cloned and ran but  no Releases are found on my machine.

do I need to run this from a specific directory?

**Comment by smithkl42** [comment]
Same here. The only command I can get to do anything interesting is "INSTALLED" (which shows about 200 or so different items, many of them entirely unconnected to Visual Studio, e.g., three entries for Windows Live Writer). Other than that, I'm mystified so far. Other commands all return errors like, "Index was outside the bounds of the array", "Object reference not set to an instance of an object", or an empty list.

**Comment by tobyhu87** [comment]
Hi guys, sorry for the delay, we finally have some free cycle to work on this.  I have a pending PR to address this issue.

Happy holiday!
Toby.

**Comment by smithkl42** [comment]
A few additional notes:
- The readme.md doesn't seem to be formatted correctly - several of the lists don't seem to be showing up correctly.
- The directions are still at a very high level. What exactly, for instance, is the syntax for the various commands?
- Related, I can't get the `load` command to work. I use `dir c:\source\thirdparty\VisualStudioUninstaller\DataFiles` to set the directory (that seems to work), and then `load "Microsoft Visual Studio Enterprise 2015.bin"` to load the appropriate .bin file, but it returns the error, "Object reference not set to an instance of an object."

**Comment by tobyhu87** [comment]
Hi Smithkl42,

The null reference exception should be addressed by https://github.com/Microsoft/VisualStudioUninstaller/pull/9/files .  I just merged it in 5 hours ago.  Please let me know if that's not the case.

thanks
toby

**Comment by CreatedJustToMessage** [comment]
The null reference exception was not addressed. It is still throwing and giving the "Object reference not set to an instance of an object" error.

**Comment by tobyhu87** [comment]
I have found the issue, and created a PR to fix it.

thanks
toby.

**Comment by tobyhu87** [comment]
Thank you for reporting this issue. The latest drop of Uninstaller knows all public releases of Visual Studio 2013 and above.  It is much simpler to use now, check out the usage in the release link below.

Release link: https://github.com/Microsoft/VisualStudioUninstaller/releases

**Comment by smithkl42** [comment]
Thank you! I don't need it at the moment, but with the new version of VS on the horizon, I could easily see needing this again.

**Comment by edgar007** [comment]
I need to leave VS 2013 intact. How can I uninstall only VS 2015?

**Comment by tobyhu87** [comment]
Hi Edgar,

Unfortunately, there are shared components between VS 2013 and VS 2015.  Ref-counting was implemented for shared components.  It is not a good idea to completely remove VS 2015, because it removes the shared components as well.  That will break VS 2013.

Total Uninstaller is designed to remove VS 2013/2015/Future entirely, so nothing left behind (things might get left behind, due to bad ref-counting or installer errors, etc.)  If you need to leave VS 2013 intact, and need to uninstall VS 2015; please uninstall VS 2015 via ARP first.

thanks
toby.
